### ISSUE TITLE
Kubernetes-POD

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Docker-Kubernetes#28]
Create and deploy a POD using declarative .yaml file. 
Create a Readme.md file explaining the steps.
Optionally, you may add output in the Readme.md file 😄

**Comment by Danondso** [comment]
@NishkarshRaj I'll give this one a shot if no one has taken it. I've worked with kube and docker but never managed a deployment myself.

**Comment by NishkarshRaj** [comment]
> 
> 
> @NishkarshRaj I'll give this one a shot if no one has taken it. I've worked with kube and docker but never managed a deployment myself.

**Comment by NishkarshRaj** [comment]
@Danondso 
Sure, do work on it. 😄 
Nobody has started working on this issue yet.

**Comment by abhishekcrdsa7** [comment]
Has this issue been resolved? I would like to work on this.

**Comment by Danondso** [comment]
Sorry I never followed up on this issue. I've done the work and submitted this [PR](https://github.com/NishkarshRaj/Docker-Kubernetes/pull/41) for it.

**Comment by NishkarshRaj** [comment]
@Danondso yeah sorry I left this open.
@abhishekcrdsa7 you might try other issues still left unresolved 👍
