### ISSUE TITLE
Docker-ENV

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Docker-Kubernetes#29]
Set up environment variables in Dockerfile at this [link](https://github.com/NishkarshRaj/Docker-Kubernetes/tree/master/Docker-Practical/6_Dockerfile)
Create Docker Image
Print the environment variables values using echo in containers.

**Comment by JasonSarwar** [comment]
Can I work on this?

**Comment by NishkarshRaj** [comment]
Ofcourse, @JasonSarwar
Do work on it and feel free to contact if you face any issue.

**Comment by JasonSarwar** [comment]
Thank you!

**Comment by NishkarshRaj** [comment]
Thanks @JasonSarwar for solving this issue.

**Comment by JasonSarwar** [comment]
Thank you very much! Glad to finally be part of the open source community!

**Comment by NishkarshRaj** [comment]
Your welcome 😄 
Feel free to query about any problems you might face in the future.
My mail is on my profile 👍
