### ISSUE TITLE
Kubernetes-Rback

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Docker-Kubernetes#33]
Create an Rback object to illustrate security mechanism in Kubernetes cluster.

**Comment by pranavbaitule** [comment]
I worked on this please see PR #43

**Comment by pranavbaitule** [comment]
Do you mind adding hacktoberfest as a topic to this repo so my PR would be counted? lol :)

**Comment by NishkarshRaj** [comment]
@pranavbaitule If you have signed up for Hacktoberfest with your GitHub account, it will be automatically counted!

Don't worry 😉
