### ISSUE TITLE
Docker-Workdir

### ISSUE THREAD

**Issue by NishkarshRaj** [NishkarshRaj/Docker-Kubernetes#34]
Create a Dockerfile and modify the default working directory from /root to some other directory (preferrably some new directory created by RUN with mkdir).

**Comment by jamesgiu** [comment]
https://github.com/NishkarshRaj/Docker-Kubernetes/pull/38
👍

**Comment by NishkarshRaj** [comment]
Thanks @jamesgiu for solving this issue 😄
